In [1]:
import pandas as pd
import numpy as np
import json
import os

print("All libraries imported successfully!")

# Check if data files exist
files = [
    '../data/docs.json',
    '../data/queries_train.json',
    '../data/queries_test.json',
    '../data/qgts_train.json'
    # if does not work use below
    # '/data/docs.json',
    # '/data/queries_train.json',
    # '/data/queries_test.json',
    # '/data/qgts_train.json'
]

print("\nchecking files...")

for file_path in files:
    if os.path.exists(file_path):
        print(f"found: {file_path}")
    else:
        print(f" MISSING: {file_path} (check your folder structure)")

All libraries imported successfully!

checking files...
found: ../data/docs.json
found: ../data/queries_train.json
found: ../data/queries_test.json
found: ../data/qgts_train.json

### Data Loading & Inspection:
- docs.json is a library of $`questions`$ posted online that we want to search through.(creating DataFrames)

In [17]:
# load documents
dataframe_docs=pd.read_json("../data/docs.json")
print(len(dataframe_docs))

# load train queries
dataframe_train=pd.read_json("../data/queries_train.json")
print(len(dataframe_train))

# load test queries
dataframe_test=pd.read_json("../data/queries_test.json")
print(len(dataframe_test))

# load qgts->queries ground truths -> it is a dictionnary not a list. 
# so we load it as a raw dictionnary
with open("../data/qgts_train.json","r") as f:
    ground_truth=json.load(f)
print(len(ground_truth))

216041
327
141
327

In [48]:
# top 5 rows of docs.json using jupyter 'display' to veiw as a nice table
display(dataframe_docs.head())

# display train queries
display(dataframe_train.head())

# show one answer from the qgts(queries ground truths)
# code below: from ground_truth dictionnary, it extract the first key into a list.
first_query_id = list(ground_truth.keys())[0]
print(f"for Query ID '{first_query_id}' :")
display(ground_truth[first_query_id])

,id,text,title,tags,category
0,6970cbf2-ffff-4c7b-b73d-52524000c232_145427,I try to install Complete MiKTeX 2.9 But there...,MikTex Download Failure - toptesi.tar.lzma,[miktex],tex
1,667220d0-66be-4059-ae60-b9df15d285f7_77850,I'm trying to get a launcher working for the W...,Launcher for a Python program that requires ex...,"[gnome3, python, path, cd]",unix
2,e5608645-f23d-4cf4-bda6-46071510ebb0_84546,Its unclear as to whether this trait means tha...,"How does the ""Double damage in combat"" trait w...",[ftl-faster-than-light],gaming
3,367fcce1-2ed8-4a95-81e4-77e30c1a37eb_154499,I am writing a thesis with specific margin req...,"Compiling with ""latex"" instead of ""pdflatex"" c...","[margins, geometry]",tex
4,75fcda1e-9b8e-4d95-bbd9-770dd6f011cc_41849,I always see job positions for web companies f...,Machine Learning Web Jobs,"[job-definition, artificial-intelligence]",programmers

,id,text,title,tags,category
0,961c4349-8cf1-4ef1-89cc-24d20bb9d000_67878,Want to try reformatting Damaged SD Card,,"[linux, development]",android
1,4008ed78-e66e-4d89-9c3b-c79bd1cf6fc9_366,"Convince grep to output all lines, not just th...",,"[shell, virtualization, storage, cluster]",unix
2,d5a95b09-e8ea-44dd-993d-347ed418e1f1_15138,How can I automatically reject some types of c...,,"[linux, development]",android
3,3e66798a-b7fd-41b5-8bc0-33b3d7ce2aca_177487,Left and right braces on different lines of align,,"[tikz-pgf, horizontal-alignment, tikz-trees]",tex
4,f5f944d2-277a-481d-ab09-612890402ded_137489,How do you get the purple shark fin?,,[skyrim],gaming

for Query ID '961c4349-8cf1-4ef1-89cc-24d20bb9d000_67878' :

{'total_relevant_docs': 4,
 'relevant_doc_ids': [{'doc_id': '135f5fdb-bcba-40b8-b90d-823617f1e805_21141',
   'relevance': 1},
  {'doc_id': 'd0609dab-fbf2-4838-be6a-05e76b291258_30322', 'relevance': 1},
  {'doc_id': 'cccd8617-6417-44a5-9f67-d4b7001b7165_47263', 'relevance': 1},
  {'doc_id': 'b953c47d-7a5f-4541-bf66-c8c645f179e2_44205', 'relevance': 1}],
 'category': 'android'}

Why relevance is usually 1

In this dataset:

- 1 = relevant

- 0 = not listed (implicitly irrelevant)

Some datasets use:

- 0, 1, 2 (graded relevance)

- but here it’s binary relevance